apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: raaghav99/raaghav_backend:latest
          ports:
            - containerPort: 5000
          env:
            - name: MONGO_URI
              # CHANGED: was "value: hardcoded-uri" now reading from Secret
              valueFrom:
                secretKeyRef:
                  name: app-secret   # name of our secret.yaml
                  key: MONGO_URI     # key inside the secret
            - name: PORT
              # CHANGED: was not here before, now reading from ConfigMap
              valueFrom:
                configMapKeyRef:
                  name: app-config   # name of our configmap.yaml
                  key: PORT          # key inside the configmap
            - name: NODE_ENV
              # CHANGED: was not here before, now reading from ConfigMap
              valueFrom:
                configMapKeyRef:
                  name: app-config   # name of our configmap.yaml
                  key: NODE_ENV      # key inside the configmap
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: dev
spec:
  selector:
    app: backend
  ports:
    - port: 5000
      targetPort: 5000