name: Dev Pipeline

on:
  push:
    branches:
      - dev

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to DockerHub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build frontend dev image
        working-directory: ./Aproject/frontend
        run: |
          echo "VITE_API_URL=http://localhost:8080" > .env
          docker build -t raaghav99/raaghav_frontend:dev .

      - name: Build backend image
        working-directory: ./Aproject/backend
        run: docker build -t raaghav99/raaghav_backend:latest .

      - name: Push images to DockerHub
        run: |
          docker push raaghav99/raaghav_frontend:dev
          docker push raaghav99/raaghav_backend:latest

      - name: Deploy to dev
        run: |
          helm upgrade email-collector-dev ~/my-project-k8s/helm/email-collector \
            -f ~/my-project-k8s/helm/email-collector/values-dev.yaml \
            -n dev
